baseURL = 'https://test.martinec.co.uk/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[menu]
  [[menu.main]]
    # Display name
    name = "Posts"
    
    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 1